[project]
name = "perfect-chapathi-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cv>=1.0.0",
    "cvzone>=1.6.1",
    "numpy>=2.2.6",
    "opencv-python-headless==4.12.0.88",
    "streamlit>=1.48.0",
]
